version: '3.8'

services:
  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: serve

  # Code Weaver service
  weaver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-weaver
    volumes:
      # Mount local directory for working with files
      - ./workspace:/workspace
      # Mount config
      - ./config.yaml:/home/weaver/.config/weaver/config.yaml
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: ["/bin/sh"]

  # Optional: Ollama Web UI
  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  default:
    name: weaver-network