# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'codeweaver-api'
    static_configs:
      - targets: ['localhost:8080']
        
  - job_name: 'codeweaver-web'
    static_configs:
      - targets: ['localhost:3000']